POST http://127.0.0.1:8080/playground
Content-Type: application/json

{
  "code": "let a = 4\nprint(a)"
}

###

POST http://127.0.0.1:8080/playground
Content-Type: application/json

{
  "code": "let totalGem = 4\nvar collected = 0\n\nfunc turnRight() {\n    turnLeft()\n    turnLeft()\n    turnLeft()\n}\n\nwhile collected < totalGem {\n    if isOnGem {\n        collectGem()\n        collected += 1\n    }\n    if isOnClosedSwitch {\n        toggleSwitch()\n    }\n    if !isBlockedRight {\n        turnRight()\n        moveForward()\n    } else {\n        if isBlocked {\n            while isBlocked {\n                turnLeft()\n            }\n        }\n        moveForward()\n    }\n}"
}