POST http://127.0.0.1:8080/paidiki-xara
Content-Type: application/json

{
  "code": "cst p = Player()\ncst s = Specialist()\nfor _ in 1 ... 3 {\ns.moveForward()\n}\nfor _ in 1 ... 3 {\ns.moveForward()\n}\ns.collectGem()\nfor _ in 1 ... 3 {\nif p.isOnBeeper {\np.takeBeeper()\n}\nmoveForward()\n}\nfor _ in 1 ..< 3 {\np.moveForward()\n}\np.collectGem()\np.dropBeeper()",
  "grid": [
    [
      "OPEN",
      "OPEN",
      "OPEN",
      "OPEN",
      "BLOCKED",
      "OPEN",
      "BLOCKED",
      "OPEN"
    ],
    [
      "OPEN",
      "WATER",
      "TREE",
      "BLOCKED",
      "TREE",
      "OPEN",
      "BLOCKED",
      "OPEN"
    ],
    [
      "OPEN",
      "WATER",
      "BLOCKED",
      "DESERT",
      "BLOCKED",
      "OPEN",
      "BLOCKED",
      "OPEN"
    ],
    [
      "OPEN",
      "DESERT",
      "OPEN",
      "OPEN",
      "BLOCKED",
      "OPEN",
      "BLOCKED",
      "OPEN"
    ]
  ],
  "layout": [
    [
      "NONE",
      "BEEPER",
      "NONE",
      "PORTAL",
      "NONE",
      "GEM",
      "NONE",
      "PORTAL"
    ],
    [
      "NONE",
      "NONE",
      "NONE",
      "NONE",
      "NONE",
      "NONE",
      "NONE",
      "NONE"
    ],
    [
      "NONE",
      "NONE",
      "NONE",
      "NONE",
      "NONE",
      "NONE",
      "NONE",
      "NONE"
    ],
    [
      "PORTAL",
      "NONE",
      "GEM",
      "NONE",
      "NONE",
      "PORTAL",
      "NONE",
      "NONE"
    ]
  ],
  "layout2s": [
    {
      "x": 4,
      "y": 3,
      "color": "YELLOW",
      "level": 0
    }
  ],
  "portals": [
    {
      "coo": {
        "x": 7,
        "y": 0
      },
      "dest": {
        "x": 5,
        "y": 3
      },
      "isActive": true
    },
    {
      "coo": {
        "x": 5,
        "y": 3
      },
      "dest": {
        "x": 7,
        "y": 0
      },
      "isActive": true
    },
    {
      "coo": {
        "x": 3,
        "y": 0
      },
      "dest": {
        "x": 0,
        "y": 3
      },
      "isActive": true
    },
    {
      "coo": {
        "x": 3,
        "y": 0
      },
      "dest": {
        "x": 0,
        "y": 3
      },
      "isActive": true
    }
  ],
  "locks": [
  ],
  "players": [
    {
      "id": 1,
      "x": 0,
      "y": 0,
      "dir": "RIGHT",
      "role": "PLAYER"
    },
    {
      "id": 2,
      "x": 7,
      "y": 3,
      "dir": "UP",
      "role": "SPECIALIST"
    }
  ]
}

###

POST http://127.0.0.1:8080/paidiki-xara
Content-Type: application/json

{
  "code": "cst p = Player()\np.moveForward()\np.takeBeeper()\np.moveForward()",
  "grid": [
    [
      "OPEN",
      "OPEN",
      "OPEN",
      "OPEN",
      "BLOCKED",
      "OPEN",
      "BLOCKED",
      "OPEN"
    ],
    [
      "OPEN",
      "WATER",
      "TREE",
      "BLOCKED",
      "TREE",
      "OPEN",
      "BLOCKED",
      "OPEN"
    ],
    [
      "OPEN",
      "WATER",
      "BLOCKED",
      "DESERT",
      "BLOCKED",
      "OPEN",
      "BLOCKED",
      "OPEN"
    ],
    [
      "OPEN",
      "DESERT",
      "OPEN",
      "OPEN",
      "BLOCKED",
      "OPEN",
      "BLOCKED",
      "OPEN"
    ]
  ],
  "layout": [
    [
      "NONE",
      "BEEPER",
      "NONE",
      "PORTAL",
      "NONE",
      "GEM",
      "NONE",
      "PORTAL"
    ],
    [
      "NONE",
      "NONE",
      "NONE",
      "NONE",
      "NONE",
      "NONE",
      "NONE",
      "NONE"
    ],
    [
      "NONE",
      "NONE",
      "NONE",
      "NONE",
      "NONE",
      "NONE",
      "NONE",
      "NONE"
    ],
    [
      "PORTAL",
      "NONE",
      "GEM",
      "NONE",
      "NONE",
      "PORTAL",
      "NONE",
      "NONE"
    ]
  ],
  "layout2s": [
    {
      "x": 4,
      "y": 3,
      "color": "YELLOW",
      "level": 0
    }
  ],
  "portals": [
    {
      "coo": {
        "x": 7,
        "y": 0
      },
      "dest": {
        "x": 5,
        "y": 3
      },
      "isActive": true
    },
    {
      "coo": {
        "x": 5,
        "y": 3
      },
      "dest": {
        "x": 7,
        "y": 0
      },
      "isActive": true
    },
    {
      "coo": {
        "x": 3,
        "y": 0
      },
      "dest": {
        "x": 0,
        "y": 3
      },
      "isActive": true
    },
    {
      "coo": {
        "x": 3,
        "y": 0
      },
      "dest": {
        "x": 0,
        "y": 3
      },
      "isActive": true
    }
  ],
  "locks": [
  ],
  "players": [
    {
      "id": 1,
      "x": 0,
      "y": 0,
      "dir": "RIGHT",
      "role": "PLAYER"
    },
    {
      "id": 2,
      "x": 7,
      "y": 3,
      "dir": "UP",
      "role": "SPECIALIST"
    }
  ]
}

###



###



###